### ISSUE TITLE
Error when running `python codeaide.py test`

### ISSUE THREAD

**Issue by zhuangjun1981** [dougollerenshaw/CodeAIde#18]
I tried to install and run the test. Here is what I encountered.

 1. when run `python codeaide.py test`, it says there is no PyQt5, I had to `pip install pyqt5`
 2. then if I run `python codeaide.py test`, I got this error:

```Clearing output directory: C:\Users\wood_\PycharmProjects\CodeAIde\generated_code
Traceback (most recent call last):
  File "codeaide.py", line 24, in <module>
    main()
  File "codeaide.py", line 10, in main
    success, message = chat_handler.test_api_connection()
AttributeError: 'ChatHandler' object has no attribute 'test_api_connection'
```
I tried the "add_tests" branch, still not working, same error.

**Comment by dougollerenshaw** [comment]
Fixed in #19. Marking closed.
